### ISSUE TITLE
Dose not work on preview N  2

### ISSUE THREAD

**Issue by enuoCM** [googlesamples/android-DirectBoot#1]
Pre-conditions

Android SDK Preview N 2
Nexus 6P(Build number: NPC91K)

Result:
Alarm scheduled at "04-22 18:41"
But only got log after unlock the device:
04-22 18:42:29.821  4523  4523 I BootBroadcastReceiver: Received action: android.intent.action.LOCKED_BOOT_COMPLETED, user unlocked: true

**Comment by thagikura** [comment]
Hi,

Thanks for your report. I'll have a look at it once I get a preview N2 device.

**Comment by thagikura** [comment]
Sorry for the delayed response. Confirmed it worked with the developer preview 3.

Also if you receive the `android.intent.action.LOCKED_BOOT_COMPLETED` intent, it means the app worked from the DirectBoot point of view.
Because that only the directBootAware components can receive that intent.

Please let me know if you still have further questions.
